// Local exclusion policy for skill exports.
//
// Shared by value like the export transaction protocol: Ploinky keeps this
// file at cli/utils/skills/exportExclusions.mjs and Explorer a byte-identical
// copy at explorer/utils/server/skill-export-exclusions.mjs. Only Node
// built-ins may be imported.
//
// Git targets never receive tracked `.gitignore` writes or rules in the shared
// `info/exclude`. The worktree's private config points `core.excludesFile` at
// a Ploinky-managed file inside that worktree's private Git directory. Git
// reads exactly one effective excludes file, so a live external excludes
// policy is never shadowed unless this invocation authorizes composition.
// Non-git folders may keep a managed `.gitignore` block backed by a receipt.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

export const IGNORE_MARKER_START = '# >>> ploinky default-skills >>>';
export const IGNORE_MARKER_END = '# <<< ploinky default-skills <<<';
export const IGNORE_RECEIPT = path.join('.agents', '.ploinky-ignore-receipt.json');
export const MANAGED_EXCLUDES = 'ploinky-skill-exports.exclude';
export const COMPOSITION_RECORD = 'ploinky-skill-exports.exclusions.json';
export const GIT_CONFIG_LOCK = 'ploinky-skill-exports-config.lock';
const RECORD_PROTOCOL = 'ploinky-skill-exclusions';
const MANAGED_HEADER = '# Generated by Ploinky for skill exports in this worktree only.\n# Editing this file hands control back to you; Ploinky then leaves it unchanged.\n';

const sha256 = bytes => crypto.createHash('sha256').update(bytes).digest('hex');

// ---------------------------------------------------------------------------
// Git access.

const GIT_ENVIRONMENT_OVERRIDES = ['GIT_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_COMMON_DIR', 'GIT_OBJECT_DIRECTORY', 'GIT_PREFIX'];

export function runGit(args, { cwd, input, env = process.env } = {}) {
    const environment = { ...env, GIT_OPTIONAL_LOCKS: '0', LC_ALL: 'C', GIT_TERMINAL_PROMPT: '0' };
    for (const name of GIT_ENVIRONMENT_OVERRIDES) delete environment[name];
    const result = spawnSync('git', ['-c', 'core.fsmonitor=false', '-c', 'core.hooksPath=/dev/null', ...args], { cwd, input, env: environment, encoding: 'buffer', timeout: 30000, maxBuffer: 64 * 1024 * 1024 });
    if (result.error) throw result.error;
    return { status: result.status, stdout: result.stdout, stderr: result.stderr.toString('utf8') };
}

const text = result => result.stdout.toString('utf8');

function ancestorHasGitEntry(root) {
    for (let directory = root; ; directory = path.dirname(directory)) {
        if (fs.lstatSync(path.join(directory, '.git'), { throwIfNoEntry: false })) return true;
        if (path.dirname(directory) === directory) return false;
    }
}

// Identity of the Git worktree containing `folder`, or null outside Git.
// Only a positive "not a git repository" with no `.git` entry above the
// target counts as outside Git; every other failure (safe.directory refusal,
// discovery limits, a damaged `.git`, no git binary) is `unavailable`.
export function resolveGitIdentity(folder, { git = runGit } = {}) {
    const root = fs.realpathSync(folder);
    let probe;
    try { probe = git(['rev-parse', '--is-inside-work-tree'], { cwd: root }); } catch (error) {
        return { root, unavailable: true, reason: `git could not run: ${error.code || error.message}` };
    }
    if (probe.status !== 0) {
        if (/not a git repository/i.test(probe.stderr) && !ancestorHasGitEntry(root)) return null;
        return { root, unavailable: true, reason: probe.stderr.trim() || `git rev-parse exited with ${probe.status}` };
    }
    if (text(probe).trim() !== 'true') return { root, insideWorkTree: false };
    const fields = git(['rev-parse', '--path-format=absolute', '--show-toplevel', '--absolute-git-dir', '--git-common-dir', '--git-path', 'config.worktree'], { cwd: root });
    if (fields.status !== 0) throw new Error(`git rev-parse failed in ${root}: ${fields.stderr.trim()}`);
    const [topLevel, gitDir, commonDir, worktreeConfig] = text(fields).split('\n').map(value => value.trim());
    const canonical = value => { try { return fs.realpathSync(value); } catch (_) { return path.resolve(value); } };
    const identity = {
        root,
        insideWorkTree: true,
        topLevel: canonical(topLevel),
        gitDir: canonical(gitDir),
        commonDir: canonical(commonDir),
        worktreeConfig: path.join(canonical(path.dirname(worktreeConfig)), path.basename(worktreeConfig)),
    };
    identity.linked = identity.gitDir !== identity.commonDir;
    identity.relative = path.relative(identity.topLevel, root).split(path.sep).filter(Boolean).join('/');
    return identity;
}

// Literal gitignore pattern anchored at the top level. Every wildcard,
// bracket, backslash and trailing space is escaped; links have no slash.
export function escapeIgnorePattern(relative) {
    if (/[\n\r]/.test(relative)) return null;
    let escaped = relative.split('/').map(part => part.replace(/[\\*?[\]]/g, match => `\\${match}`)).join('/');
    escaped = escaped.replace(/ +$/, spaces => spaces.replace(/ /g, '\\ '));
    return `/${escaped}`;
}

function configValues(file, key, git, cwd) {
    if (!fs.existsSync(file)) return [];
    const result = git(['config', '--file', file, '--get-all', key], { cwd });
    if (result.status === 1) return [];
    if (result.status !== 0) throw new Error(`git config --file ${file} failed: ${result.stderr.trim()}`);
    return text(result).split('\n').filter(value => value !== '');
}

function readRegular(file) {
    const stat = fs.lstatSync(file, { throwIfNoEntry: false });
    if (!stat || !stat.isFile()) return null;
    return fs.readFileSync(file);
}

function expandPath(value, base, env) {
    if (value === '~' || value.startsWith('~/')) return path.join(env.HOME || os.homedir(), value.slice(1));
    return path.isAbsolute(value) ? value : path.resolve(base, value);
}

function trustedHostConfigOrigin(scope, origin, env) {
    if (scope === 'default') return true;
    if (!origin.startsWith('file:')) return false;
    const canonical = file => { try { return fs.realpathSync(file); } catch (_) { return path.resolve(file); } };
    const home = env.HOME || os.homedir();
    const expected = scope === 'global'
        ? (env.GIT_CONFIG_GLOBAL ? [env.GIT_CONFIG_GLOBAL] : [path.join(home, '.gitconfig'), path.join(env.XDG_CONFIG_HOME || path.join(home, '.config'), 'git', 'config')])
        : scope === 'system' ? [env.GIT_CONFIG_SYSTEM || '/etc/gitconfig'] : [];
    return expected.some(file => canonical(file) === canonical(origin.slice('file:'.length)));
}

// The excludes file Git would use here without a worktree-scope value.
// An unreadable policy still exists: treating it as absent would hide it
// behind our private file. The host also must not copy content selected by
// repository-local config outside the selected workspace.
export function inheritedExcludes(identity, { git = runGit, env = process.env, gitDirBoundary = null, authorizeComposition = false } = {}) {
    const result = git(['config', '--show-scope', '--show-origin', '-z', '--get-all', 'core.excludesFile'], { cwd: identity.root, env });
    const entries = [];
    if (result.status === 0) {
        const parts = text(result).split('\0');
        for (let index = 0; index + 2 < parts.length; index += 3) entries.push({ scope: parts[index], origin: parts[index + 1], value: parts[index + 2] });
    }
    if (result.status !== 0 && result.status !== 1) throw new Error(`Git could not identify the inherited excludes policy: ${result.stderr.trim()}`);
    const inherited = entries.filter(entry => entry.scope !== 'worktree' && entry.scope !== 'command').pop();
    let file;
    let scope;
    let origin;
    if (inherited) {
        file = expandPath(inherited.value, identity.topLevel, env);
        scope = inherited.scope;
        origin = inherited.origin;
    } else {
        const xdg = env.XDG_CONFIG_HOME;
        file = xdg ? path.join(xdg, 'git', 'ignore') : path.join(env.HOME || os.homedir(), '.config', 'git', 'ignore');
        scope = 'default';
        origin = xdg ? 'XDG_CONFIG_HOME' : 'HOME';
    }
    const policy = { scope, origin, path: file, digest: null, bytes: null, live: true };
    const unavailable = (code, reason) => ({ ...policy, unavailable: { code, reason } });
    const repositorySelected = !['global', 'system', 'default'].includes(scope);
    if (gitDirBoundary && repositorySelected && !insideBoundary(gitDirBoundary, path.resolve(file))) {
        return unavailable('exclusions-source-outside-boundary', `The repository-selected excludes file ${file} is outside ${gitDirBoundary}; the host will not read or compose it.`);
    }
    if (gitDirBoundary && !repositorySelected && !trustedHostConfigOrigin(scope, origin, env)) {
        return unavailable('exclusions-origin-unverified', `The inherited excludes policy comes from an included or unverified ${scope} configuration (${origin}); it is left unchanged.`);
    }
    let descriptor;
    try {
        const entry = fs.lstatSync(file, { throwIfNoEntry: false });
        if (!entry) return { ...policy, live: false };
        const resolved = fs.realpathSync(file);
        if (gitDirBoundary && repositorySelected && !insideBoundary(gitDirBoundary, resolved)) {
            return unavailable('exclusions-source-outside-boundary', `The repository-selected excludes file ${file} resolves outside ${gitDirBoundary}; the host will not read or compose it.`);
        }
        // Even a valid host policy needs consent on this invocation. A
        // workspace-writable receipt cannot grant access to host file bytes.
        if (gitDirBoundary && !authorizeComposition) return policy;
        const stat = fs.statSync(resolved);
        if (!stat.isFile()) return unavailable('exclusions-source-unavailable', `The inherited excludes file ${file} is not a regular file; it is left unchanged.`);
        descriptor = fs.openSync(resolved, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
        if (!fs.fstatSync(descriptor).isFile()) return unavailable('exclusions-source-unavailable', `The inherited excludes file ${file} is not a regular file; it is left unchanged.`);
        const bytes = fs.readFileSync(descriptor);
        return { ...policy, digest: sha256(bytes), bytes, live: Boolean(bytes.toString('utf8').trim()) };
    } catch (error) {
        return unavailable('exclusions-source-unavailable', `The inherited excludes file ${file} could not be verified (${error.code || error.message}); it is left unchanged.`);
    } finally {
        if (descriptor !== undefined) fs.closeSync(descriptor);
    }
}

// One disposable fixture per process proves that this Git keeps worktree
// config private to its worktree once extensions.worktreeConfig is enabled.
let capabilityCache = null;
export function worktreeConfigCapability({ git = runGit } = {}) {
    if (capabilityCache) return capabilityCache;
    const base = fs.mkdtempSync(path.join(os.tmpdir(), 'ploinky-worktree-config-'));
    const env = { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: path.join(base, 'global') };
    fs.writeFileSync(env.GIT_CONFIG_GLOBAL, '');
    const run = (args, cwd) => {
        const result = git(args, { cwd, env });
        if (result.status !== 0) throw new Error(result.stderr.trim());
        return text(result).trim();
    };
    try {
        const main = path.join(base, 'main');
        fs.mkdirSync(main);
        run(['init', '-q'], main);
        run(['-c', 'user.name=probe', '-c', 'user.email=probe@invalid', 'commit', '-q', '--allow-empty', '-m', 'probe'], main);
        run(['worktree', 'add', '-q', '-b', 'probe', path.join(base, 'linked')], main);
        run(['config', 'extensions.worktreeConfig', 'true'], main);
        const linked = path.join(base, 'linked');
        const file = run(['rev-parse', '--path-format=absolute', '--git-path', 'config.worktree'], linked);
        run(['config', '--file', file, 'core.excludesFile', '/probe'], linked);
        const origin = git(['config', '--show-origin', '--get', 'core.excludesFile'], { cwd: linked, env });
        const mainValue = git(['config', '--get', 'core.excludesFile'], { cwd: main, env });
        const ok = origin.status === 0 && text(origin).includes('config.worktree') && text(origin).trim().endsWith('/probe') && mainValue.status === 1;
        capabilityCache = ok ? { supported: true } : { supported: false, reason: 'worktree config was not private in a disposable fixture' };
    } catch (error) {
        capabilityCache = { supported: false, reason: error.message };
    } finally {
        fs.rmSync(base, { recursive: true, force: true });
    }
    return capabilityCache;
}

// ---------------------------------------------------------------------------
// Non-git managed block.

export function managedBlock(patterns) {
    return `${IGNORE_MARKER_START}\n${patterns.join('\n')}\n${IGNORE_MARKER_END}\n`;
}

function readReceipt(root) {
    try {
        const bytes = readRegular(path.join(root, IGNORE_RECEIPT));
        if (!bytes) return null;
        const receipt = JSON.parse(bytes.toString('utf8'));
        if (receipt?.protocol !== RECORD_PROTOCOL || receipt.path !== '.gitignore' || typeof receipt.block !== 'string' || typeof receipt.after !== 'string') return null;
        return receipt;
    } catch (_) {
        return null;
    }
}

const receiptBytes = receipt => `${JSON.stringify(receipt, null, 2)}\n`;

// Current bytes with the receipt's exact block removed, or null when the
// block is not present exactly once.
function withoutReceiptBlock(bytes, receipt) {
    const content = bytes.toString('utf8');
    const first = content.indexOf(receipt.block);
    if (first < 0 || content.indexOf(receipt.block, first + 1) >= 0) return null;
    return Buffer.from(content.slice(0, first) + content.slice(first + receipt.block.length));
}

function planNonGit(root, patterns, options) {
    const gitignore = path.join(root, '.gitignore');
    const stat = fs.lstatSync(gitignore, { throwIfNoEntry: false });
    if (stat && !stat.isFile()) return { outcome: { status: 'preserved', mode: 'non-git', code: 'gitignore-not-regular-file', reason: `${gitignore} is not a regular file; it is left unchanged.` }, artifacts: [] };
    const current = stat ? fs.readFileSync(gitignore) : null;
    const receipt = readReceipt(root);
    const block = managedBlock(patterns);
    const hasMarkers = current !== null && current.toString('utf8').includes(IGNORE_MARKER_START);
    let base;
    if (hasMarkers) {
        if (!receipt || sha256(current) !== receipt.after) {
            return { outcome: { status: 'preserved', mode: 'non-git', code: 'unverified-ignore-block-preserved', reason: `${gitignore} has a Ploinky marker block without a matching write receipt; it is left unchanged. Remove the block by hand to let Ploinky manage it again.` }, artifacts: [] };
        }
        base = withoutReceiptBlock(current, receipt);
        if (base === null) return { outcome: { status: 'preserved', mode: 'non-git', code: 'unverified-ignore-block-preserved', reason: `${gitignore} no longer contains the recorded block exactly once.` }, artifacts: [] };
    } else {
        if (!options.nonGitBlock) return { outcome: { status: 'unchanged', mode: 'non-git' }, artifacts: [] };
        base = current ?? Buffer.alloc(0);
    }
    const prefix = base.length && !base.toString('utf8').endsWith('\n') ? '\n' : '';
    const next = Buffer.from(base.toString('utf8') + prefix + block);
    if (current !== null && next.equals(current)) return { outcome: { status: 'unchanged', mode: 'non-git' }, artifacts: [] };
    const beforeAbsent = hasMarkers ? Boolean(receipt.beforeAbsent) : current === null;
    const nextReceipt = {
        protocol: RECORD_PROTOCOL, version: 1, path: '.gitignore',
        before: beforeAbsent ? null : sha256(base), beforeAbsent,
        after: sha256(next), block: prefix + block,
    };
    return {
        outcome: { status: 'published', mode: 'non-git' },
        artifacts: [
            { kind: 'gitignore', bytes: next },
            { kind: 'receipt', bytes: Buffer.from(receiptBytes(nextReceipt)) },
        ],
    };
}

// ---------------------------------------------------------------------------
// Git private excludes.

function readRecord(file) {
    try {
        const bytes = readRegular(file);
        if (!bytes) return null;
        const record = JSON.parse(bytes.toString('utf8'));
        return record?.protocol === RECORD_PROTOCOL ? record : null;
    } catch (_) {
        return null;
    }
}

function writable(target) {
    try { fs.accessSync(target, fs.constants.W_OK); return true; } catch (_) { return false; }
}

function deferred(code, reason, extra = {}) {
    return { outcome: { status: 'deferred', mode: 'git', code, reason, ...extra }, artifacts: [] };
}

function broadRules(identity, git) {
    const probe = [identity.relative, '.agents', 'skills', '.ploinky-visibility-probe'].filter(Boolean).join('/');
    const result = git(['check-ignore', '-v', '--no-index', '--', probe], { cwd: identity.topLevel });
    if (result.status !== 0) return [];
    const line = text(result).split('\n')[0];
    const match = /^(.*?):(\d+):(.*)\t/.exec(line);
    if (!match) return [];
    const source = path.resolve(identity.topLevel, match[1]);
    if (source === path.join(identity.gitDir, MANAGED_EXCLUDES)) return [];
    return [{ source: match[1], line: Number(match[2]), pattern: match[3] }];
}

// Undo a previous non-git block after the folder became a Git worktree. Only
// an untracked file whose bytes match the receipt is changed.
function planGitInitMigration(identity, git) {
    const receipt = readReceipt(identity.root);
    if (!receipt) return { artifacts: [], warnings: [] };
    const gitignore = path.join(identity.root, '.gitignore');
    const current = readRegular(gitignore);
    if (!current || sha256(current) !== receipt.after) return { artifacts: [], warnings: [] };
    const tracked = git(['ls-files', '--error-unmatch', '--', '.gitignore'], { cwd: identity.root }).status === 0;
    if (tracked) {
        return { artifacts: [], warnings: [{ code: 'unverified-ignore-block-preserved', reason: `${gitignore} is tracked with a Ploinky block; it is repository policy now and is left unchanged.` }] };
    }
    const base = withoutReceiptBlock(current, receipt);
    if (base === null || (receipt.before !== null && sha256(base) !== receipt.before)) return { artifacts: [], warnings: [] };
    return {
        artifacts: [
            { kind: 'gitignore', bytes: receipt.beforeAbsent && base.length === 0 ? null : base },
            { kind: 'receipt', bytes: null },
        ],
        warnings: [],
    };
}

function insideBoundary(boundary, candidate) {
    const relative = path.relative(boundary, candidate);
    return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}

// Containers see their own HOME, XDG and global Git configuration, not the
// repository owner's, so they cannot prove which excludes policy is live.
export function detectContainerExecutor() {
    return ['/run/.containerenv', '/.dockerenv'].some(marker => { try { return fs.existsSync(marker); } catch (_) { return false; } });
}

// Resolve less-trusted metadata without asking Git to load its configuration.
// This runs before lock discovery as well as before every host publication.
function assertHostGitBoundary(root, boundary) {
    const reject = (code, reason) => {
        const error = new Error(reason);
        error.code = 'SKILL_EXPORT_HOST_BOUNDARY';
        error.exclusionCode = code;
        throw error;
    };
    const inspect = (candidate, directory = false) => {
        const absolute = path.resolve(candidate);
        if (!insideBoundary(boundary, absolute)) reject('git-directory-outside-boundary', `Git metadata resolves outside ${boundary}; nothing is written.`);
        let current = boundary;
        const parts = path.relative(boundary, absolute).split(path.sep).filter(Boolean);
        for (let index = 0; index < parts.length; index++) {
            current = path.join(current, parts[index]);
            const stat = fs.lstatSync(current, { throwIfNoEntry: false });
            if (!stat) return null;
            const needsDirectory = index < parts.length - 1 || directory;
            if (stat.isSymbolicLink() || (needsDirectory ? !stat.isDirectory() : !stat.isFile() || stat.nlink !== 1)) {
                reject('git-metadata-not-private-regular', `Git metadata is linked or not a private regular path: ${current}; nothing is written.`);
            }
        }
        return absolute;
    };
    const read = filename => {
        inspect(filename);
        const fd = fs.openSync(filename, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK);
        try {
            const stat = fs.fstatSync(fd);
            if (!stat.isFile() || stat.nlink !== 1 || stat.size > 1024 * 1024) reject('git-metadata-not-private-regular', `Git metadata is not a bounded private file: ${filename}`);
            return fs.readFileSync(fd, 'utf8');
        } finally { fs.closeSync(fd); }
    };
    inspect(root, true);
    let top = root;
    for (;;) {
        const entry = path.join(top, '.git');
        const stat = fs.lstatSync(entry, { throwIfNoEntry: false });
        if (stat) {
            let gitDir;
            if (stat.isDirectory()) gitDir = entry;
            else {
                const match = /^gitdir: ([^\r\n]+)\r?\n?$/.exec(read(entry));
                if (!match) reject('git-metadata-invalid', `Git metadata pointer is invalid: ${entry}`);
                gitDir = path.resolve(top, match[1]);
            }
            inspect(gitDir, true);
            const commonFile = path.join(gitDir, 'commondir');
            const commonDir = fs.lstatSync(commonFile, { throwIfNoEntry: false })
                ? path.resolve(gitDir, read(commonFile).trim()) : gitDir;
            inspect(commonDir, true);
            for (const file of new Set([path.join(commonDir, 'config'), path.join(commonDir, 'config.worktree'), path.join(gitDir, 'config.worktree')])) {
                if (inspect(file) && /^\s*\[\s*include(?:if)?\b/im.test(read(file))) reject('git-config-include-unverified', `Repository Git includes cannot be used by host exclusion refresh: ${file}`);
            }
            for (const file of [MANAGED_EXCLUDES, COMPOSITION_RECORD]) inspect(path.join(gitDir, file));
            return;
        }
        if (top === boundary) return;
        top = path.dirname(top);
    }
}

function planGit(identity, patterns, options) {
    const { git, env } = options;
    if (identity.unavailable) return deferred('git-identity-unavailable', `Git could not identify the repository containing ${identity.root} (${identity.reason}); nothing is written and no .gitignore is created.`);
    if (!identity.insideWorkTree) return deferred('git-target-unsupported', `${identity.root} is inside a Git directory, not a worktree.`);
    if (options.containerExecutor) return deferred('exclusions-executor-view-unverified', `This process runs in a container or agent sandbox whose HOME, XDG and global Git configuration can differ from the repository owner's, so it cannot prove which excludes policy is live. Private exclusions for ${identity.topLevel} are left unchanged; run the operation from the host to refresh them.`);
    // A caller that received the folder from less trusted content (the host
    // refreshing Box-reported folders) confines Git metadata to its boundary:
    // a planted `.git` file must not redirect writes outside it.
    if (options.gitDirBoundary && ![identity.topLevel, identity.gitDir, identity.commonDir].every(dir => insideBoundary(options.gitDirBoundary, dir))) {
        return deferred('git-directory-outside-boundary', `The Git metadata for ${identity.root} resolves outside ${options.gitDirBoundary}; nothing is written.`);
    }
    if (!options.heldGitLocks.includes(identity.commonDir)) return deferred('git-metadata-lock-missing', `The common Git configuration lock for ${identity.commonDir} is not held; exclusions are deferred.`);
    const capability = options.capability({ git });
    if (!capability.supported) return deferred('git-worktree-config-unsupported', `This Git cannot keep worktree configuration private (${capability.reason}); no shared rules are written.`);
    const commonConfig = path.join(identity.commonDir, 'config');
    const mainWorktreeConfig = path.join(identity.commonDir, 'config.worktree');
    const managedFile = path.join(identity.gitDir, MANAGED_EXCLUDES);
    const recordFile = path.join(identity.gitDir, COMPOSITION_RECORD);
    const cwd = identity.root;
    for (const file of new Set([commonConfig, mainWorktreeConfig, identity.worktreeConfig])) {
        const nativeLock = `${file}.lock`;
        if (fs.lstatSync(nativeLock, { throwIfNoEntry: false })) {
            return deferred('git-config-busy', `Git configuration has an existing lock at ${nativeLock}; it is preserved and exclusions are deferred.`);
        }
    }
    const values = (file, key) => configValues(file, key, git, cwd);
    for (const target of [commonConfig, identity.gitDir, identity.commonDir, ...[identity.worktreeConfig, managedFile, recordFile].filter(fs.existsSync)]) {
        if (!writable(target)) return deferred('git-config-read-only', `${target} is not writable; exclusions are deferred and nothing is changed.`);
    }
    const extension = values(commonConfig, 'extensions.worktreeConfig');
    const enabled = extension.length > 0 && ['true', 'yes', 'on', '1'].includes(extension[extension.length - 1].toLowerCase());
    if (extension.length && !enabled) return deferred('worktree-config-disabled', `extensions.worktreeConfig is explicitly '${extension.at(-1)}' in ${commonConfig}; it is left unchanged.`);

    const artifacts = [];
    const migrationUnsets = [];
    if (!enabled) {
        // Documented migration: the main worktree's core.worktree, and
        // core.bare=true, move to its config.worktree before other worktrees
        // stop inheriting them. Enabled first, unset last.
        for (const key of ['core.worktree', 'core.bare']) {
            const common = values(commonConfig, key);
            if (!common.length || (key === 'core.bare' && common.at(-1).toLowerCase() !== 'true')) continue;
            const existing = values(mainWorktreeConfig, key);
            if (existing.length && existing.at(-1) !== common.at(-1)) return deferred('worktree-config-migration-conflict', `${key} differs between ${commonConfig} and ${mainWorktreeConfig}; resolve it before enabling extensions.worktreeConfig.`);
            if (!existing.length) artifacts.push({ kind: 'git-config', file: mainWorktreeConfig, key, before: [], after: [common.at(-1)] });
            migrationUnsets.push({ kind: 'git-config', file: commonConfig, key, before: common, after: [] });
        }
        artifacts.push({ kind: 'git-config', file: commonConfig, key: 'extensions.worktreeConfig', before: extension, after: ['true'] });
        artifacts.push(...migrationUnsets);
    }

    const current = values(identity.worktreeConfig, 'core.excludesFile');
    const record = readRecord(recordFile);
    // A relocated worktree still carries our record next to the managed file;
    // the stale absolute path is re-resolved rather than treated as foreign.
    const relocated = current.length === 1 && current[0] !== managedFile && record?.excludesFile === current[0]
        && path.basename(current[0]) === MANAGED_EXCLUDES;
    const managed = current.length === 1 && (current[0] === managedFile || relocated);
    if (current.length && !managed) {
        return { outcome: { status: 'relinquished', mode: 'git', code: 'worktree-excludes-user-managed', reason: `core.excludesFile in ${identity.worktreeConfig} is set by someone else; it is left unchanged.` }, artifacts: [] };
    }
    if (managed) {
        const bytes = readRegular(managedFile);
        if (!record || (record.excludesFile !== managedFile && !relocated) || !bytes || sha256(bytes) !== record.composedDigest) {
            return { outcome: { status: 'relinquished', mode: 'git', code: 'managed-excludes-edited', reason: `${managedFile} or its record changed outside Ploinky; the edit is preserved and Ploinky no longer updates it.` }, artifacts: [] };
        }
    }
    const inherited = inheritedExcludes(identity, { git, env, gitDirBoundary: options.gitDirBoundary, authorizeComposition: options.authorizeComposition });
    const authorized = options.authorizeComposition === true;
    if (inherited.unavailable || (inherited.live && !authorized)) {
        const code = inherited.unavailable?.code || 'exclusions-deferred';
        const reason = inherited.unavailable?.reason || `The effective excludes file ${inherited.path} (${inherited.scope}) would be shadowed by a private worktree excludes file. It is left unchanged, so generated skill links may show as untracked. Set PLOINKY_SKILL_EXCLUDES_COMPOSE=1 for each invocation that may compose it into a private file (later edits to ${inherited.path} are picked up on the next authorized update, not live).`;
        if (managed) {
            // Hand the shadowed policy back: restore the absent key only while it is still ours.
            return { outcome: { status: 'deferred', mode: 'git', code, reason, relinquished: true }, artifacts: [{ kind: 'git-config', file: identity.worktreeConfig, key: 'core.excludesFile', before: current, after: [] }] };
        }
        return deferred(code, reason);
    }
    const composed = Buffer.from(MANAGED_HEADER + patterns.join('\n') + '\n'
        + (inherited.live ? `\n# Previously effective excludes: ${inherited.path}\n${inherited.bytes.toString('utf8')}${inherited.bytes.toString('utf8').endsWith('\n') ? '' : '\n'}` : ''));
    const rules = broadRules(identity, git);
    const warnedBefore = new Set((record?.broadRules || []).map(rule => JSON.stringify(rule)));
    const warnings = rules.filter(rule => !warnedBefore.has(JSON.stringify(rule))).map(rule => ({
        code: 'broad-ignore-rule', reason: `Ignore rule '${rule.pattern}' in ${rule.source}:${rule.line} hides every file under .agents/skills; locally authored skills there stay hidden.`, rule,
    }));
    const migration = planGitInitMigration(identity, git);
    warnings.push(...migration.warnings);
    const nextRecord = {
        protocol: RECORD_PROTOCOL, version: 1,
        excludesFile: managedFile, configFile: identity.worktreeConfig,
        previous: record?.previous ?? { present: current.length > 0 && !managed, values: managed ? [] : current },
        inherited: { scope: inherited.scope, origin: inherited.origin, path: inherited.path, digest: inherited.digest },
        authorized,
        composedDigest: sha256(composed),
        configFingerprint: sha256(JSON.stringify([identity.worktreeConfig, managedFile, 'true'])),
        broadRules: rules,
    };
    artifacts.push({ kind: 'private-file', path: managedFile, bytes: composed });
    artifacts.push({ kind: 'private-file', path: recordFile, bytes: Buffer.from(`${JSON.stringify(nextRecord, null, 2)}\n`) });
    if (!managed || relocated) artifacts.push({ kind: 'git-config', file: identity.worktreeConfig, key: 'core.excludesFile', before: current, after: [managedFile] });
    artifacts.push(...migration.artifacts);
    return {
        outcome: { status: 'published', mode: 'git', composed: inherited.live, warnings },
        artifacts,
        state: { mode: 'git', identity, previous: nextRecord.previous, inherited: nextRecord.inherited, sourceDigest: inherited.digest, composedDigest: nextRecord.composedDigest, configFingerprint: nextRecord.configFingerprint },
    };
}

/** Planner used by the export transaction. `ownedPaths` are root-relative
 * paths of verified owned output, computed by the transaction under its
 * locks; nothing here infers ownership from names or link targets.
 */
export function createSkillExclusionPlanner({ authorizeComposition = false, nonGitBlock = false, git = runGit, env = process.env, capability = worktreeConfigCapability, containerExecutor = detectContainerExecutor(), gitDirBoundary = null } = {}) {
    const boundary = gitDirBoundary ? fs.realpathSync(gitDirBoundary) : null;
    return {
        hostBoundary: boundary,
        assertSafeTarget(folder) {
            if (boundary) assertHostGitBoundary(path.resolve(folder), boundary);
        },
        commonDir(folder) {
            this.assertSafeTarget(folder);
            try { const identity = resolveGitIdentity(folder, { git }); return identity?.insideWorkTree ? identity.commonDir : null; } catch (_) { return null; }
        },
        plan(input) {
            try {
                return this.planUnchecked(input);
            } catch (error) {
                // Exclusions never abort the export itself.
                return { outcome: { status: 'deferred', mode: 'unknown', code: 'exclusions-planning-failed', reason: `Local exclusions could not be planned: ${error.message}` }, artifacts: [], state: { mode: 'unknown', identity: null } };
            }
        },
        planUnchecked({ root, ownedPaths, heldGitLocks = [] }) {
            this.assertSafeTarget(root);
            const identity = resolveGitIdentity(root, { git });
            const prefix = identity?.insideWorkTree ? identity.relative : '';
            const patterns = [];
            const unrepresentable = [];
            for (const relative of [...new Set(ownedPaths)].sort()) {
                const pattern = escapeIgnorePattern([prefix, relative].filter(Boolean).join('/'));
                if (pattern) patterns.push(pattern); else unrepresentable.push(relative);
            }
            const planned = identity
                ? planGit(identity, patterns, { git, env, authorizeComposition, capability, heldGitLocks, containerExecutor, gitDirBoundary: boundary })
                : planNonGit(root, patterns, { nonGitBlock });
            if (unrepresentable.length) planned.outcome.unrepresentable = unrepresentable;
            // The folder lets a host process act on a deferral from a container.
            planned.outcome.folder = root;
            planned.state ||= { mode: identity ? 'git' : 'non-git', identity: identity || null };
            return planned;
        },
    };
}

// ---------------------------------------------------------------------------
// Pre-pull assessment.

function statusEntries(repoPath, git) {
    const tracked = git(['status', '--porcelain=v1', '-z', '--untracked-files=no'], { cwd: repoPath });
    if (tracked.status !== 0) throw new Error(`git status failed in ${repoPath}: ${tracked.stderr.trim()}`);
    const entries = [];
    const parts = text(tracked).split('\0');
    for (let index = 0; index < parts.length; index++) {
        const item = parts[index];
        if (item.length < 4) continue;
        const code = item.slice(0, 2);
        entries.push({ code, path: item.slice(3) });
        if (code[0] === 'R' || code[0] === 'C') index++;
    }
    const untracked = git(['ls-files', '-z', '--others', '--exclude-standard', '--', ':(glob).gitignore', ':(glob)**/.gitignore'], { cwd: repoPath });
    if (untracked.status === 0) for (const item of text(untracked).split('\0').filter(Boolean)) entries.push({ code: '??', path: item });
    return entries;
}

/** Called before a verified Git update classifies a checkout as dirty.
 * Restores a `.gitignore` only when an exact write receipt matches both its
 * current bytes and the index; everything else is preserved and reported.
 */
export function assessGeneratedIgnoreState({ repoPath, git = runGit } = {}) {
    const identity = resolveGitIdentity(repoPath, { git });
    if (!identity?.insideWorkTree) return { status: 'none' };
    const top = identity.topLevel;
    const candidates = statusEntries(top, git).filter(entry => path.posix.basename(entry.path) === '.gitignore');
    const restored = [];
    const preserved = [];
    for (const entry of candidates) {
        const file = path.join(top, entry.path);
        const current = readRegular(file);
        if (!current || !current.toString('utf8').includes(IGNORE_MARKER_START)) continue;
        const preserve = (code, reason) => preserved.push({ path: entry.path, code, reason });
        const [staged, worktree] = entry.code;
        if (staged === 'U' || worktree === 'U' || entry.code === 'AA' || entry.code === 'DD') { preserve('ignore-file-conflicted', `${entry.path} is conflicted; resolve the conflict before updating.`); continue; }
        if (entry.code !== '??' && staged !== ' ') { preserve('staged-ignore-change-preserved', `${entry.path} has staged changes; commit or unstage them before updating.`); continue; }
        const receipt = readReceipt(path.dirname(file));
        if (!receipt || sha256(current) !== receipt.after) {
            preserve('unverified-ignore-block-preserved', `${entry.path} contains a Ploinky marker block with no matching write receipt, so it may hold your edits. Inspect it, then commit it or restore it with 'git restore -- ${entry.path}' before updating.`);
            continue;
        }
        const base = withoutReceiptBlock(current, receipt);
        if (base === null || (receipt.before !== null && sha256(base) !== receipt.before)) { preserve('unverified-ignore-block-preserved', `${entry.path} no longer matches its write receipt.`); continue; }
        let target;
        if (entry.code === '??') {
            if (!receipt.beforeAbsent || base.length) { preserve('unverified-ignore-block-preserved', `${entry.path} is untracked and holds content Ploinky did not write.`); continue; }
            target = null;
        } else {
            const index = git(['show', `:0:${entry.path}`], { cwd: top });
            if (index.status !== 0 || !index.stdout.equals(base)) { preserve('unverified-ignore-block-preserved', `${entry.path} differs from the index beyond the recorded Ploinky block.`); continue; }
            target = index.stdout;
        }
        // Compare before write: the bytes must still be the receipt's bytes.
        const temporary = `${file}.${crypto.randomUUID()}.tmp`;
        try {
            if (target !== null) fs.writeFileSync(temporary, target, { flag: 'wx', mode: fs.statSync(file).mode & 0o777 });
            const again = readRegular(file);
            if (!again || !again.equals(current)) { preserve('unverified-ignore-block-preserved', `${entry.path} changed during assessment.`); continue; }
            if (target === null) fs.unlinkSync(file); else fs.renameSync(temporary, file);
        } finally {
            fs.rmSync(temporary, { force: true });
        }
        fs.rmSync(path.join(path.dirname(file), IGNORE_RECEIPT), { force: true });
        restored.push(entry.path);
    }
    if (preserved.length) return { status: 'preserve', code: preserved[0].code, reason: preserved.map(item => item.reason).join(' '), paths: preserved.map(item => item.path), preserved, restored };
    if (restored.length) return { status: 'restored', paths: restored };
    return { status: 'none' };
}
