import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import os from 'node:os';
import path from 'node:path';
import { verifyLaunchedHardwareLimits } from '../../cli/sandbox/hardwareLimits/delegation.mjs';
import { admitManifestRuntimeCapabilities, hardwareLimitsHashOf, createHardwareLaunchGuard } from '../../cli/sandbox/runtimeCapabilities.js';
import { applyHardwareLimits, hardwareApplyIsUnchanged } from '../../cli/sandbox/hardwareLimits/reconcile.mjs';
import { preparedCgroupFs } from '../hardware-limits/fakeCgroupFs.mjs';
import { BOX_MARKER_CONTENT } from '../../ploinky-box/constants.mjs';
test('Apply rechecks current kernel limits before returning unchanged', async (t) => {
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'apply-drift-'));
t.after(() => fs.rmSync(root, { recursive: true, force: true }));
const markerPath = root + '/box-marker';
fs.writeFileSync(markerPath, BOX_MARKER_CONTENT);
const token = { epoch: '1'.repeat(32), revision: 1 };
const context = { gate: 'on', prepared: true, backendReady: true, controllers: ['cpu', 'memory', 'pids'], storeState: 'valid', storeToken: token, overrides: new Map(), envelope: { cpus: 8, memoryBytes: 16 * 1024 ** 3 } };
const admission = admitManifestRuntimeCapabilities({container:'node:20-alpine',llmRuntime:{runtimePolicy:{resources:{memory:'512m',cpus:0.5,pidsLimit:128}}}}, { agentId:'demo/worker', runtime:'podman', hardwareContext:context, boxMarkerOptions:{markerPath}, workspaceRoot:root });
const fake = preparedCgroupFs();
fake.addGroup('/ploinky/agents', {uid:1000});
const leaf = '/ploinky/agents/libpod-a';
fake.addGroup(leaf, {uid:1000});
fake.placePid(321, leaf);
fake.readlinkSync = target => target === '/proc/self/ns/cgroup' ? 'cgroup:[1000]' : 'cgroup:[2000]';
for (const [key,value] of Object.entries({'memory.max':String(512*1024**2),'memory.swap.max':'0','cpu.max':'50000 100000','pids.max':'128'})) fake.groups.get(leaf).values.set(key,value);
const containerId = 'a'.repeat(64);
const record = {type:'agent',repoName:'demo',agentName:'worker',instanceId:'instance-1',enableGeneration:'generation-1',containerId};
let proof;
const guard = createHardwareLaunchGuard(admission, { key:'exact',ref:'demo/worker',hardwareContext:context,fsApi:fake,query:()=>({ok:true,stdout:'321\n'}),instanceId:record.instanceId,enableGeneration:record.enableGeneration,recordApplied:value=>{proof=value;} });
guard.afterLaunch({containerId});
assert.equal(proof.limitsHash,hardwareLimitsHashOf(admission.descriptor));
fake.groups.get(leaf).values.set('memory.max','max');
let rejection;
try {guard.afterLaunch({containerId});}catch(error){rejection=error.code;}
assert.equal(rejection,'PLOINKY_HARDWARE_LIMITS_UNENFORCEABLE');
let reconciliations=0;
const observed = {loadRouting:()=>({}), inspect:()=>({state:'exact',id:containerId,running:true}), readApplied:()=>proof, readLabel:()=>proof.limitsHash, verifyLimits:(options)=>verifyLaunchedHardwareLimits({...options,fsApi:fake,query:()=>({ok:true,stdout:'321\n'})})};
const result = await applyHardwareLimits({expectedToken:token,containers:['exact']},{ lease:(_options,callback)=>callback(),loadRegistry:()=>({exact:record}),loadRouting:()=>({}),readPolicy:()=>({token}),policyCheck:()=>({token}),loadPlan:()=>({runtime:'podman',runtimeAdmission:admission,profileResolution:{network:{mode:'default'}}}),isUnchanged:(captured,plan)=>hardwareApplyIsUnchanged(captured,plan,observed),reconcile:()=>{reconciliations++;return {key:'exact',state:'applied'};} });
console.log(JSON.stringify({currentMemoryMax:fake.groups.get(leaf).values.get('memory.max'),strictReadback:rejection,applyStatus:result.status,result:result.results[0],reconciliations}));
assert.equal(result.results[0].state,'applied');
assert.equal(reconciliations,1);
fake.groups.get(leaf).values.set('memory.max',String(512*1024**2));
assert.equal(hardwareApplyIsUnchanged({key:'exact',record},{runtime:'podman',runtimeAdmission:admission},observed),true);
});
